parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Application\Handler\:
    resource: '../../../Application/Handler/*'
    public: true

  App\Infrastructure\Http\Handler\:
    resource: '../../Http/Handler/*'
    public: true

  App\Application\Contract\Bus\QueryBus:
    class: App\Infrastructure\Application\Bus\QueryBus
    arguments:
      - '@messenger.bus.query'
