parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  messenger.senders_locator:
    class: Symfony\Component\Messenger\Transport\Sender\SendersLocator
    arguments:
      - []
    public: true

  App\Application\Handler\:
    resource: '../../../Application/Handler/*'
    tags: [messenger.message_handler]
    public: true

  App\Infrastructure\Http\Handler\:
    resource: '../../Http/Handler/*'
    public: true

  App\Application\EventListener\:
    resource: '../../../Application/EventListener/*'
    tags: [event_dispatcher.listener]

  App\Application\MessageBus\Recorder\EventRecorder:
    public: true

  event_recorders:
    alias: App\Application\MessageBus\Recorder\EventRecorder
    public: true

  messender.middleware.handle_message_middleware:
    class: App\Infrastructure\Application\MessageBus\Middleware\HandleMessageWithEventRecorederMiddleware
    arguments:
      - '@messenger.handlers_locator'
      - '@event_recorders'
    public: true

  messender.middleware.logging_middleware:
    class: Symfony\Component\Messenger\Middleware\LoggingMiddleware
    arguments:
      - '@Psr\Log\LoggerInterface'
    public: true

  messender.middleware.send_message_middleware:
    class: Symfony\Component\Messenger\Middleware\SendMessageMiddleware
    arguments:
      - '@messenger.senders_locator'
    public: true

  messender.middleware.release_recorded_events_middleware:
    class: App\Infrastructure\Application\MessageBus\Middleware\ReleaseRecordedEventsMiddleware
    public: true
