parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  messenger.senders_locator:
    class: Symfony\Component\Messenger\Transport\Sender\SendersLocator
    arguments:
      - []
    public: true

  App\Application\Handler\:
    resource: '../../../Application/Handler/*'
    tags: [messenger.message_handler]
    public: true

  App\Infrastructure\Http\Handler\:
    resource: '../../Http/Handler/*'
    public: true
