parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  messenger.senders_locator:
    class: Symfony\Component\Messenger\Transport\Sender\SendersLocator
    arguments:
      - []
    public: true

  command_handlers:
    namespace: App\Application\MessageHandler\
    resource: '../../../Application/MessageHandler/*CommandHandler.php'
    tags:
      - { name: messenger.message_handler, bus: messenger.bus.commands }
    public: true

  query_handlers:
    namespace: App\Application\MessageHandler\
    resource: '../../../Application/MessageHandler/*QueryHandler.php'
    tags:
      - { name: messenger.message_handler, bus: messenger.bus.queries }
    public: true

  App\Infrastructure\Http\Handler\:
    resource: '../../Http/Handler/*'
    public: true

  App\Infrastructure\Http\Middleware\:
    resource: '../../Http/Middleware/*'
    public: true

  App\Application\EventListener\:
    resource: '../../../Application/EventListener/*'
    tags: [event_dispatcher.listener]

  App\Application\Identifier\UuidEncoder:
    public: true

  App\Application\MessageBus\Recorder\EventRecorder:
    public: true

  event_recorders:
    alias: App\Application\MessageBus\Recorder\EventRecorder
    public: true

  validation:
    alias: Symfony\Component\Validator\Validator\ValidatorInterface
    public: true

  messenger.handlers_locator:
    class: Symfony\Component\Messenger\Handler\HandlersLocator
    arguments:
      - []

  messenger.bus.queries.middleware.handle_message:
    class: App\Infrastructure\Application\MessageBus\Middleware\HandleMessageWithEventRecorederMiddleware
    arguments:
      - '@messenger.handlers_locator'
      - '@event_recorders'
    public: true

  messenger.bus.commands.middleware.handle_message:
    class: App\Infrastructure\Application\MessageBus\Middleware\HandleMessageWithEventRecorederMiddleware
    arguments:
      - '@messenger.handlers_locator'
      - '@event_recorders'
    public: true

  messenger.middleware.logging:
    class: Symfony\Component\Messenger\Middleware\LoggingMiddleware
    arguments:
      - '@Psr\Log\LoggerInterface'
    public: true

  messenger.middleware.send_message:
    class: Symfony\Component\Messenger\Middleware\SendMessageMiddleware
    arguments:
      - '@messenger.senders_locator'
    public: true

  messenger.middleware.release_recorded_events:
    class: App\Infrastructure\Application\MessageBus\Middleware\ReleaseRecordedEventsMiddleware
    public: true

  messenger.middleware.validation:
    class: Symfony\Component\Messenger\Middleware\ValidationMiddleware
    arguments:
      - '@validation'
    public: true

  messenger.middleware.doctrine_transaction:
    class: App\Infrastructure\Application\MessageBus\Middleware\DoctrineTransactionMiddleware
    arguments:
      - '@doctrine.entitymanager'
    public: true
